/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../components/ble/connection`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ble/utils/proto`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/cards/createcards`; params?: Router.UnknownInputParams; } | { pathname: `/cards/createtypes`; params?: Router.UnknownInputParams; } | { pathname: `/cards`; params?: Router.UnknownInputParams; } | { pathname: `/cards/mycards`; params?: Router.UnknownInputParams; } | { pathname: `/config/firebaseConfig`; params?: Router.UnknownInputParams; } | { pathname: `/providers/AuthProvider`; params?: Router.UnknownInputParams; } | { pathname: `/sharing`; params?: Router.UnknownInputParams; } | { pathname: `/sharing/receiver`; params?: Router.UnknownInputParams; } | { pathname: `/sharing/sender`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../components/ble/connection`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ble/utils/proto`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/cards/createcards`; params?: Router.UnknownOutputParams; } | { pathname: `/cards/createtypes`; params?: Router.UnknownOutputParams; } | { pathname: `/cards`; params?: Router.UnknownOutputParams; } | { pathname: `/cards/mycards`; params?: Router.UnknownOutputParams; } | { pathname: `/config/firebaseConfig`; params?: Router.UnknownOutputParams; } | { pathname: `/providers/AuthProvider`; params?: Router.UnknownOutputParams; } | { pathname: `/sharing`; params?: Router.UnknownOutputParams; } | { pathname: `/sharing/receiver`; params?: Router.UnknownOutputParams; } | { pathname: `/sharing/sender`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/../components/ble/connection${`?${string}` | `#${string}` | ''}` | `/../components/ble/utils/proto${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-up${`?${string}` | `#${string}` | ''}` | `/sign-up${`?${string}` | `#${string}` | ''}` | `${'/(home)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/cards/createcards${`?${string}` | `#${string}` | ''}` | `/cards/createtypes${`?${string}` | `#${string}` | ''}` | `/cards${`?${string}` | `#${string}` | ''}` | `/cards/mycards${`?${string}` | `#${string}` | ''}` | `/config/firebaseConfig${`?${string}` | `#${string}` | ''}` | `/providers/AuthProvider${`?${string}` | `#${string}` | ''}` | `/sharing${`?${string}` | `#${string}` | ''}` | `/sharing/receiver${`?${string}` | `#${string}` | ''}` | `/sharing/sender${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../components/ble/connection`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ble/utils/proto`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/cards/createcards`; params?: Router.UnknownInputParams; } | { pathname: `/cards/createtypes`; params?: Router.UnknownInputParams; } | { pathname: `/cards`; params?: Router.UnknownInputParams; } | { pathname: `/cards/mycards`; params?: Router.UnknownInputParams; } | { pathname: `/config/firebaseConfig`; params?: Router.UnknownInputParams; } | { pathname: `/providers/AuthProvider`; params?: Router.UnknownInputParams; } | { pathname: `/sharing`; params?: Router.UnknownInputParams; } | { pathname: `/sharing/receiver`; params?: Router.UnknownInputParams; } | { pathname: `/sharing/sender`; params?: Router.UnknownInputParams; };
    }
  }
}
